### ISSUE TITLE
apcupsd: determine if short dates are day-first or month-first

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/apcupsd#8]
It would appear that the UPS can report dates such as January 2, 2006 as `1/2/2006` or `2/1/2006`, and we have no way of determining which is correct at the moment.  Perhaps it's a good idea to suggest some configuration setting, or perhaps there's a way to always work this out based on other information in the request.

**Comment by donvipre** [comment]
excerpt from apcupsd-3.14.14-5.el7.x86_64 (CentOS 7)
/etc/apcupsd/apcupsd.conf:
```
#
# ========== Configuration statements used in updating the UPS EPROM =========
#

#
# These statements are used only by apctest when choosing "Set EEPROM with conf
# file values" from the EEPROM menu. THESE STATEMENTS HAVE NO EFFECT ON APCUPSD.
#

# UPS name, max 8 characters 
#UPSNAME UPS_IDEN

# Battery date - 8 characters
#BATTDATE mm/dd/yy
```

**Comment by mdlayher** [comment]
Due to format ambiguities, this is now always a string. https://github.com/mdlayher/apcupsd/commit/149abe0674c282fb1cba644fe2a758ae6ca14bc8
